-- JobFinder Phase 2: tabel jobs. Pengunjung (anon) hanya boleh MEMBACA.
-- Tulis/ubah data hanya lewat dashboard Supabase atau service role (server/n8n), tidak pernah dari frontend.
create table public.jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  company text not null,
  location text,
  city text,
  description text,
  requirements text[] not null default '{}',
  source_name text,
  source_url text,
  posted_date timestamptz,
  discovered_date timestamptz not null default now(),
  category text,
  salary_min integer,
  salary_max integer,
  employment_type text,
  work_mode text,
  tags text[] not null default '{}',
  ai_relevance_score integer check (ai_relevance_score between 0 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Mencegah lowongan ganda dari tautan yang sama (dipakai di Phase 3).
create unique index jobs_source_url_key on public.jobs (source_url) where source_url is not null;
create index jobs_discovered_idx on public.jobs (discovered_date desc);
create index jobs_category_idx on public.jobs (category);
create index jobs_city_idx on public.jobs (city);

alter table public.jobs enable row level security;
create policy "jobs_public_read" on public.jobs for select to anon, authenticated using (true);

create function public.set_updated_at() returns trigger language plpgsql set search_path = '' as $$
begin new.updated_at = now(); return new; end $$;
create trigger jobs_updated_at before update on public.jobs for each row execute function public.set_updated_at();
