-- Data dummy. Dijalankan pada tabel kosong agar id 1..9 sesuai js/data.js.
insert into public.jobs (title,company,location,city,description,requirements,source_name,discovered_date,category,employment_type,work_mode,tags,ai_relevance_score) values
('Staff Rekam Medis','RS ABC','Jakarta Selatan','Jakarta','Mengelola berkas rekam medis rawat jalan dan rawat inap, memastikan kelengkapan dokumen, dan mendukung pelaporan rumah sakit.',array['Minimal D3 Rekam Medis','Memahami ICD-10','Memahami sistem RME','Mampu melakukan administrasi pasien']::text[],'LinkedIn',now() - interval '120 minutes','Rekam Medis','Full Time','On-site',array['rekam medis','icd-10','rme']::text[],92),
('Medical Record Staff','RS XYZ','Bekasi','Bekasi','Melakukan filing, assembling, dan retensi berkas rekam medis serta membantu proses audit internal.',array['Minimal D3 Rekam Medis','Pengalaman minimal 2 tahun','Menguasai Microsoft Office']::text[],'Website RS XYZ',now() - interval '540 minutes','Rekam Medis','Full Time','On-site',array['medical record','filing']::text[],85),
('Coder Rekam Medis','RS Sehat Sentosa','Jakarta Timur','Jakarta','Melakukan pengkodean diagnosis dan tindakan menggunakan ICD-10 dan ICD-9-CM untuk klaim pasien.',array['D3 Rekam Medis','Menguasai ICD-10 dan ICD-9-CM','Teliti dan disiplin']::text[],'Google Search',now() - interval '1800 minutes','Rekam Medis','Kontrak','On-site',array['coder','icd-10','icd-9-cm']::text[],90),
('Petugas Pendaftaran Pasien','Klinik Pratama Medika','Bandar Lampung','Lampung','Melayani pendaftaran pasien baru dan lama, verifikasi data, serta koordinasi dengan poli.',array['Minimal D3 kesehatan atau SMA sederajat','Komunikatif dan ramah','Familiar dengan SIMRS']::text[],'JobStreet',now() - interval '3120 minutes','Pendaftaran','Full Time','On-site',array['pendaftaran','front office']::text[],70),
('Staff Administrasi Rumah Sakit','RS Harapan Bunda','Tangerang','Tangerang','Mengelola surat-menyurat, arsip, dan laporan administrasi unit pelayanan.',array['Minimal D3 semua jurusan','Menguasai Microsoft Office','Pengalaman di fasilitas kesehatan menjadi nilai tambah']::text[],'Glints',now() - interval '4500 minutes','Administrasi Rumah Sakit','Full Time','On-site',array['administrasi','rumah sakit']::text[],55),
('Admin Data Klaim BPJS','RS Mitra Keluarga Bekasi','Bekasi','Bekasi','Menyiapkan berkas klaim BPJS, memeriksa kelengkapan, dan berkoordinasi dengan tim coder.',array['D3 Rekam Medis atau Kesehatan','Memahami INA-CBG','Teliti dengan angka']::text[],'LinkedIn',now() - interval '7200 minutes','Administrasi Rumah Sakit','Kontrak','On-site',array['klaim','bpjs','administrasi']::text[],68),
('Perawat Pelaksana','RS Cipta Husada','Jakarta Barat','Jakarta','Memberikan asuhan keperawatan di ruang rawat inap sesuai standar.',array['D3 atau Ners Keperawatan','STR aktif','Bersedia shift']::text[],'Website RS Cipta Husada',now() - interval '12000 minutes','Perawat','Full Time','On-site',array['perawat','nurse']::text[],10),
('Staff IT SIMRS','RS Bunda Kasih','Surabaya','Surabaya','Mendukung operasional SIMRS, menangani kendala pengguna, dan memelihara jaringan lokal.',array['D3/S1 Teknik Informatika atau Sistem Informasi','Memahami basis data','Pengalaman SIMRS']::text[],'Google Search',now() - interval '15600 minutes','IT','Full Time','On-site',array['simrs','it support']::text[],45),
('Health Information Officer (Remote)','Klinik Digital Sehat','Remote, Indonesia','Remote','Memelihara kualitas data rekam medis elektronik dan menyusun laporan statistik bulanan.',array['Latar belakang Rekam Medis dan Informasi Kesehatan','Menguasai Excel','Memahami statistik kesehatan']::text[],'Glints',now() - interval '30000 minutes','Rekam Medis','Part Time','Remote',array['medical records','health information','rme']::text[],88);
